# Generated by Django 5.2.7 on 2025-10-14 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0005_alter_persona_options_remove_persona_id_and_more'),
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='moneda_pago',
            field=models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD'), ('EUR', 'EUR')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='moneda_prestamo',
            field=models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD'), ('EUR', 'EUR')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cuotas_totales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.persona'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
