# Generated by Django 5.2.7 on 2025-10-15 09:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_prestamo_moneda_pago_prestamo_moneda_prestamo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cuotas_totales',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('400000'))]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('116'))]),
        ),
    ]
