# Generated by Django 5.2.7 on 2025-12-10 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0006_alter_persona_noti_email_alter_persona_noti_sms'),
        ('Prestamos', '0003_alter_prestamo_cuotas_totales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='banco',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='Persona.persona'),
        ),
        migrations.CreateModel(
            name='Acreedor',
            fields=[
                ('id_acreedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del acreedor: persona, banco, empresa, etc.', max_length=150)),
                ('tipo', models.CharField(choices=[('persona', 'Persona natural'), ('empresa', 'Empresa / negocio')], default='persona', max_length=20)),
                ('documento', models.CharField(blank=True, help_text='DNI o RUC del acreedor (opcional).', max_length=20)),
                ('banco', models.CharField(blank=True, help_text='Banco donde le vas a depositar (opcional).', max_length=100)),
                ('nro_cuenta', models.CharField(blank=True, help_text='N° de cuenta bancaria (opcional).', max_length=40)),
                ('nro_cci', models.CharField(blank=True, help_text='N° CCI (opcional).', max_length=40)),
                ('alias_yape', models.CharField(blank=True, help_text='Alias o nombre que usas para Yape/Plin (opcional).', max_length=50)),
                ('celular', models.CharField(blank=True, help_text='Celular para Yape/Plin u otro medio.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Correo del acreedor (opcional).', max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Usuario dueño de este acreedor (el que gestiona la deuda).', on_delete=django.db.models.deletion.CASCADE, related_name='acreedores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='acreedor',
            field=models.ForeignKey(blank=True, help_text='Persona o entidad a la que realmente le debes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='Prestamos.acreedor'),
        ),
    ]
