# Generated by Django 5.2.7 on 2025-12-10 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0004_alter_prestamo_banco_alter_prestamo_persona_acreedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acreedor',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular para Yape/Plin u otro medio (9 dígitos).', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'El celular debe tener exactamente 9 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='acreedor',
            name='documento',
            field=models.CharField(blank=True, help_text='DNI (8) o RUC (11). Solo números.', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{8,11}$', 'El documento debe contener solo números (8 para DNI o 11 para RUC).')]),
        ),
        migrations.AlterField(
            model_name='acreedor',
            name='nro_cci',
            field=models.CharField(blank=True, help_text='N° CCI (20 dígitos).', max_length=40, validators=[django.core.validators.RegexValidator('^\\d{20}$', 'El CCI debe tener exactamente 20 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='acreedor',
            name='nro_cuenta',
            field=models.CharField(blank=True, help_text='N° de cuenta bancaria (10 a 30 dígitos).', max_length=40, validators=[django.core.validators.RegexValidator('^[0-9\\- ]{10,30}$', 'La cuenta debe tener entre 10 y 30 caracteres numéricos (puede incluir espacios o guiones).')]),
        ),
    ]
