# Generated by Django 5.2.7 on 2025-12-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_pago_base_fija_pago_destino_fijo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mp_payment_id',
            field=models.CharField(blank=True, help_text='ID de pago de Mercado Pago una vez aprobado.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_preference_id',
            field=models.CharField(blank=True, help_text='ID de preferencia de Mercado Pago (Checkout Pro).', max_length=100, null=True),
        ),
    ]
