# Generated by Django 5.2.7 on 2025-10-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('base', models.CharField(max_length=3)),
                ('destino', models.CharField(max_length=3)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('obtenido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('fecha', 'base', 'destino')},
            },
        ),
    ]
