# Generated by Django 5.2.7 on 2025-10-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alerta', models.DateField()),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviada', 'Enviada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='Pagos.pago')),
            ],
        ),
    ]
