# Generated by Django 5.2.7 on 2025-10-14 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0004_alter_persona_options_remove_persona_id_persona_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AddField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='moneda_preferida',
            field=models.CharField(default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='persona',
            name='noti_dias',
            field=models.CharField(default='3,1,0', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='noti_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='noti_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
