# Generated by Django 5.2.7 on 2025-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0005_alter_persona_options_remove_persona_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='noti_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='noti_sms',
            field=models.BooleanField(default=True),
        ),
    ]
